// <auto-generated />
namespace HelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _201612201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201612201));
        
        string IMigrationMetadata.Id
        {
            get { return "201612200401166_20161220-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
